/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as IntakeIndexRouteImport } from './routes/intake/index'
import { Route as ResourcesCategorySlugRouteImport } from './routes/resources/$categorySlug'
import { Route as IntakeValuesRouteImport } from './routes/intake/values'
import { Route as IntakeReviewRouteImport } from './routes/intake/review'
import { Route as IntakeResultsRouteImport } from './routes/intake/results'
import { Route as IntakePersonalityRouteImport } from './routes/intake/personality'
import { Route as IntakeChallengesRouteImport } from './routes/intake/challenges'
import { Route as IntakeBasicRouteImport } from './routes/intake/basic'
import { Route as IntakeAptitudeRouteImport } from './routes/intake/aptitude'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeIndexRoute = IntakeIndexRouteImport.update({
  id: '/intake/',
  path: '/intake/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesCategorySlugRoute = ResourcesCategorySlugRouteImport.update({
  id: '/resources/$categorySlug',
  path: '/resources/$categorySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeValuesRoute = IntakeValuesRouteImport.update({
  id: '/intake/values',
  path: '/intake/values',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeReviewRoute = IntakeReviewRouteImport.update({
  id: '/intake/review',
  path: '/intake/review',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeResultsRoute = IntakeResultsRouteImport.update({
  id: '/intake/results',
  path: '/intake/results',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakePersonalityRoute = IntakePersonalityRouteImport.update({
  id: '/intake/personality',
  path: '/intake/personality',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeChallengesRoute = IntakeChallengesRouteImport.update({
  id: '/intake/challenges',
  path: '/intake/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeBasicRoute = IntakeBasicRouteImport.update({
  id: '/intake/basic',
  path: '/intake/basic',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeAptitudeRoute = IntakeAptitudeRouteImport.update({
  id: '/intake/aptitude',
  path: '/intake/aptitude',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/intake/aptitude': typeof IntakeAptitudeRoute
  '/intake/basic': typeof IntakeBasicRoute
  '/intake/challenges': typeof IntakeChallengesRoute
  '/intake/personality': typeof IntakePersonalityRoute
  '/intake/results': typeof IntakeResultsRoute
  '/intake/review': typeof IntakeReviewRoute
  '/intake/values': typeof IntakeValuesRoute
  '/resources/$categorySlug': typeof ResourcesCategorySlugRoute
  '/intake/': typeof IntakeIndexRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/intake/aptitude': typeof IntakeAptitudeRoute
  '/intake/basic': typeof IntakeBasicRoute
  '/intake/challenges': typeof IntakeChallengesRoute
  '/intake/personality': typeof IntakePersonalityRoute
  '/intake/results': typeof IntakeResultsRoute
  '/intake/review': typeof IntakeReviewRoute
  '/intake/values': typeof IntakeValuesRoute
  '/resources/$categorySlug': typeof ResourcesCategorySlugRoute
  '/intake': typeof IntakeIndexRoute
  '/resources': typeof ResourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/intake/aptitude': typeof IntakeAptitudeRoute
  '/intake/basic': typeof IntakeBasicRoute
  '/intake/challenges': typeof IntakeChallengesRoute
  '/intake/personality': typeof IntakePersonalityRoute
  '/intake/results': typeof IntakeResultsRoute
  '/intake/review': typeof IntakeReviewRoute
  '/intake/values': typeof IntakeValuesRoute
  '/resources/$categorySlug': typeof ResourcesCategorySlugRoute
  '/intake/': typeof IntakeIndexRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/careers'
    | '/contact'
    | '/intake/aptitude'
    | '/intake/basic'
    | '/intake/challenges'
    | '/intake/personality'
    | '/intake/results'
    | '/intake/review'
    | '/intake/values'
    | '/resources/$categorySlug'
    | '/intake/'
    | '/resources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/careers'
    | '/contact'
    | '/intake/aptitude'
    | '/intake/basic'
    | '/intake/challenges'
    | '/intake/personality'
    | '/intake/results'
    | '/intake/review'
    | '/intake/values'
    | '/resources/$categorySlug'
    | '/intake'
    | '/resources'
  id:
    | '__root__'
    | '/'
    | '/careers'
    | '/contact'
    | '/intake/aptitude'
    | '/intake/basic'
    | '/intake/challenges'
    | '/intake/personality'
    | '/intake/results'
    | '/intake/review'
    | '/intake/values'
    | '/resources/$categorySlug'
    | '/intake/'
    | '/resources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  IntakeAptitudeRoute: typeof IntakeAptitudeRoute
  IntakeBasicRoute: typeof IntakeBasicRoute
  IntakeChallengesRoute: typeof IntakeChallengesRoute
  IntakePersonalityRoute: typeof IntakePersonalityRoute
  IntakeResultsRoute: typeof IntakeResultsRoute
  IntakeReviewRoute: typeof IntakeReviewRoute
  IntakeValuesRoute: typeof IntakeValuesRoute
  ResourcesCategorySlugRoute: typeof ResourcesCategorySlugRoute
  IntakeIndexRoute: typeof IntakeIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/': {
      id: '/intake/'
      path: '/intake'
      fullPath: '/intake/'
      preLoaderRoute: typeof IntakeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$categorySlug': {
      id: '/resources/$categorySlug'
      path: '/resources/$categorySlug'
      fullPath: '/resources/$categorySlug'
      preLoaderRoute: typeof ResourcesCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/values': {
      id: '/intake/values'
      path: '/intake/values'
      fullPath: '/intake/values'
      preLoaderRoute: typeof IntakeValuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/review': {
      id: '/intake/review'
      path: '/intake/review'
      fullPath: '/intake/review'
      preLoaderRoute: typeof IntakeReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/results': {
      id: '/intake/results'
      path: '/intake/results'
      fullPath: '/intake/results'
      preLoaderRoute: typeof IntakeResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/personality': {
      id: '/intake/personality'
      path: '/intake/personality'
      fullPath: '/intake/personality'
      preLoaderRoute: typeof IntakePersonalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/challenges': {
      id: '/intake/challenges'
      path: '/intake/challenges'
      fullPath: '/intake/challenges'
      preLoaderRoute: typeof IntakeChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/basic': {
      id: '/intake/basic'
      path: '/intake/basic'
      fullPath: '/intake/basic'
      preLoaderRoute: typeof IntakeBasicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/aptitude': {
      id: '/intake/aptitude'
      path: '/intake/aptitude'
      fullPath: '/intake/aptitude'
      preLoaderRoute: typeof IntakeAptitudeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  IntakeAptitudeRoute: IntakeAptitudeRoute,
  IntakeBasicRoute: IntakeBasicRoute,
  IntakeChallengesRoute: IntakeChallengesRoute,
  IntakePersonalityRoute: IntakePersonalityRoute,
  IntakeResultsRoute: IntakeResultsRoute,
  IntakeReviewRoute: IntakeReviewRoute,
  IntakeValuesRoute: IntakeValuesRoute,
  ResourcesCategorySlugRoute: ResourcesCategorySlugRoute,
  IntakeIndexRoute: IntakeIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
