/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as IntakeIndexRouteImport } from './routes/intake/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ResourcesCategorySlugRouteImport } from './routes/resources/$categorySlug'
import { Route as IntakeValuesRouteImport } from './routes/intake/values'
import { Route as IntakeReviewRouteImport } from './routes/intake/review'
import { Route as IntakeResultsRouteImport } from './routes/intake/results'
import { Route as IntakePersonalityRouteImport } from './routes/intake/personality'
import { Route as IntakeChallengesRouteImport } from './routes/intake/challenges'
import { Route as IntakeBasicRouteImport } from './routes/intake/basic'
import { Route as IntakeAptitudeRouteImport } from './routes/intake/aptitude'
import { Route as ContactJoinRouteImport } from './routes/contact/join'
import { Route as AdminUserUserIdRouteImport } from './routes/admin/user.$userId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeIndexRoute = IntakeIndexRouteImport.update({
  id: '/intake/',
  path: '/intake/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ResourcesCategorySlugRoute = ResourcesCategorySlugRouteImport.update({
  id: '/resources/$categorySlug',
  path: '/resources/$categorySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeValuesRoute = IntakeValuesRouteImport.update({
  id: '/intake/values',
  path: '/intake/values',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeReviewRoute = IntakeReviewRouteImport.update({
  id: '/intake/review',
  path: '/intake/review',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeResultsRoute = IntakeResultsRouteImport.update({
  id: '/intake/results',
  path: '/intake/results',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakePersonalityRoute = IntakePersonalityRouteImport.update({
  id: '/intake/personality',
  path: '/intake/personality',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeChallengesRoute = IntakeChallengesRouteImport.update({
  id: '/intake/challenges',
  path: '/intake/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeBasicRoute = IntakeBasicRouteImport.update({
  id: '/intake/basic',
  path: '/intake/basic',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeAptitudeRoute = IntakeAptitudeRouteImport.update({
  id: '/intake/aptitude',
  path: '/intake/aptitude',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactJoinRoute = ContactJoinRouteImport.update({
  id: '/contact/join',
  path: '/contact/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUserUserIdRoute = AdminUserUserIdRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/careers': typeof CareersRoute
  '/dashboard': typeof DashboardRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/contact/join': typeof ContactJoinRoute
  '/intake/aptitude': typeof IntakeAptitudeRoute
  '/intake/basic': typeof IntakeBasicRoute
  '/intake/challenges': typeof IntakeChallengesRoute
  '/intake/personality': typeof IntakePersonalityRoute
  '/intake/results': typeof IntakeResultsRoute
  '/intake/review': typeof IntakeReviewRoute
  '/intake/values': typeof IntakeValuesRoute
  '/resources/$categorySlug': typeof ResourcesCategorySlugRoute
  '/admin/': typeof AdminIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/intake/': typeof IntakeIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/admin/user/$userId': typeof AdminUserUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/dashboard': typeof DashboardRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/contact/join': typeof ContactJoinRoute
  '/intake/aptitude': typeof IntakeAptitudeRoute
  '/intake/basic': typeof IntakeBasicRoute
  '/intake/challenges': typeof IntakeChallengesRoute
  '/intake/personality': typeof IntakePersonalityRoute
  '/intake/results': typeof IntakeResultsRoute
  '/intake/review': typeof IntakeReviewRoute
  '/intake/values': typeof IntakeValuesRoute
  '/resources/$categorySlug': typeof ResourcesCategorySlugRoute
  '/admin': typeof AdminIndexRoute
  '/contact': typeof ContactIndexRoute
  '/intake': typeof IntakeIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/admin/user/$userId': typeof AdminUserUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/careers': typeof CareersRoute
  '/dashboard': typeof DashboardRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/contact/join': typeof ContactJoinRoute
  '/intake/aptitude': typeof IntakeAptitudeRoute
  '/intake/basic': typeof IntakeBasicRoute
  '/intake/challenges': typeof IntakeChallengesRoute
  '/intake/personality': typeof IntakePersonalityRoute
  '/intake/results': typeof IntakeResultsRoute
  '/intake/review': typeof IntakeReviewRoute
  '/intake/values': typeof IntakeValuesRoute
  '/resources/$categorySlug': typeof ResourcesCategorySlugRoute
  '/admin/': typeof AdminIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/intake/': typeof IntakeIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/admin/user/$userId': typeof AdminUserUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/careers'
    | '/dashboard'
    | '/privacy'
    | '/terms'
    | '/contact/join'
    | '/intake/aptitude'
    | '/intake/basic'
    | '/intake/challenges'
    | '/intake/personality'
    | '/intake/results'
    | '/intake/review'
    | '/intake/values'
    | '/resources/$categorySlug'
    | '/admin/'
    | '/contact/'
    | '/intake/'
    | '/resources/'
    | '/admin/user/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/dashboard'
    | '/privacy'
    | '/terms'
    | '/contact/join'
    | '/intake/aptitude'
    | '/intake/basic'
    | '/intake/challenges'
    | '/intake/personality'
    | '/intake/results'
    | '/intake/review'
    | '/intake/values'
    | '/resources/$categorySlug'
    | '/admin'
    | '/contact'
    | '/intake'
    | '/resources'
    | '/admin/user/$userId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/careers'
    | '/dashboard'
    | '/privacy'
    | '/terms'
    | '/contact/join'
    | '/intake/aptitude'
    | '/intake/basic'
    | '/intake/challenges'
    | '/intake/personality'
    | '/intake/results'
    | '/intake/review'
    | '/intake/values'
    | '/resources/$categorySlug'
    | '/admin/'
    | '/contact/'
    | '/intake/'
    | '/resources/'
    | '/admin/user/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CareersRoute: typeof CareersRoute
  DashboardRoute: typeof DashboardRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ContactJoinRoute: typeof ContactJoinRoute
  IntakeAptitudeRoute: typeof IntakeAptitudeRoute
  IntakeBasicRoute: typeof IntakeBasicRoute
  IntakeChallengesRoute: typeof IntakeChallengesRoute
  IntakePersonalityRoute: typeof IntakePersonalityRoute
  IntakeResultsRoute: typeof IntakeResultsRoute
  IntakeReviewRoute: typeof IntakeReviewRoute
  IntakeValuesRoute: typeof IntakeValuesRoute
  ResourcesCategorySlugRoute: typeof ResourcesCategorySlugRoute
  ContactIndexRoute: typeof ContactIndexRoute
  IntakeIndexRoute: typeof IntakeIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/': {
      id: '/intake/'
      path: '/intake'
      fullPath: '/intake/'
      preLoaderRoute: typeof IntakeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/resources/$categorySlug': {
      id: '/resources/$categorySlug'
      path: '/resources/$categorySlug'
      fullPath: '/resources/$categorySlug'
      preLoaderRoute: typeof ResourcesCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/values': {
      id: '/intake/values'
      path: '/intake/values'
      fullPath: '/intake/values'
      preLoaderRoute: typeof IntakeValuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/review': {
      id: '/intake/review'
      path: '/intake/review'
      fullPath: '/intake/review'
      preLoaderRoute: typeof IntakeReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/results': {
      id: '/intake/results'
      path: '/intake/results'
      fullPath: '/intake/results'
      preLoaderRoute: typeof IntakeResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/personality': {
      id: '/intake/personality'
      path: '/intake/personality'
      fullPath: '/intake/personality'
      preLoaderRoute: typeof IntakePersonalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/challenges': {
      id: '/intake/challenges'
      path: '/intake/challenges'
      fullPath: '/intake/challenges'
      preLoaderRoute: typeof IntakeChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/basic': {
      id: '/intake/basic'
      path: '/intake/basic'
      fullPath: '/intake/basic'
      preLoaderRoute: typeof IntakeBasicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/aptitude': {
      id: '/intake/aptitude'
      path: '/intake/aptitude'
      fullPath: '/intake/aptitude'
      preLoaderRoute: typeof IntakeAptitudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/join': {
      id: '/contact/join'
      path: '/contact/join'
      fullPath: '/contact/join'
      preLoaderRoute: typeof ContactJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/user/$userId': {
      id: '/admin/user/$userId'
      path: '/user/$userId'
      fullPath: '/admin/user/$userId'
      preLoaderRoute: typeof AdminUserUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUserUserIdRoute: typeof AdminUserUserIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminUserUserIdRoute: AdminUserUserIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CareersRoute: CareersRoute,
  DashboardRoute: DashboardRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ContactJoinRoute: ContactJoinRoute,
  IntakeAptitudeRoute: IntakeAptitudeRoute,
  IntakeBasicRoute: IntakeBasicRoute,
  IntakeChallengesRoute: IntakeChallengesRoute,
  IntakePersonalityRoute: IntakePersonalityRoute,
  IntakeResultsRoute: IntakeResultsRoute,
  IntakeReviewRoute: IntakeReviewRoute,
  IntakeValuesRoute: IntakeValuesRoute,
  ResourcesCategorySlugRoute: ResourcesCategorySlugRoute,
  ContactIndexRoute: ContactIndexRoute,
  IntakeIndexRoute: IntakeIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
